import './globals.css'
import { Inter } from 'next/font/google'
import Footer from './components/Footer/footer'
import Navbar from './components/Navbar/navbar'
import { ThemeProvider } from "./Context/themeContext";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider>

        <div className='container'>

        <Navbar></Navbar>
        
        {children}

        <Footer></Footer>
        </div>
        </ThemeProvider>
        </body>
    </html>
  )
}
