import './globals.css'
import { Inter } from 'next/font/google'
import Footer from './components/Footer/footer'
import Navbar from './components/Navbar/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar></Navbar>

      <h2>Main layout</h2>
        
        {children}
        
        <Footer></Footer>
        </body>
    </html>
  )
}
